 
version: "3.9"
services:

 webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./web/:/usr/share/nginx/html/:ro

    
    